### ISSUE TITLE
Example Demo will not compile Ubuntu version 24.04 and Openframeworks version 0.12.0 both fresh install

### ISSUE THREAD

**Issue by bar2098** [jvcleave/ofxImGui#126]
addons/ofxImGui/example-demo/src/ofApp.cpp:11:35: error: ‘ImGuiConfigFlags_DockingEnable’ was not declared in this scope; did you mean ‘ImGuiConfigFlags_None’?
   11 |     ImGui::GetIO().ConfigFlags |= ImGuiConfigFlags_DockingEnable;
      |                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                   ImGuiConfigFlags_None

Also another error when attempting to compile app that uses this addon 

addons/ofxImGui/src/Helpers.cpp:28:37: error: ‘struct ofxImGui::WindowOpen’ has no member named ‘usedNames’
   28 |         while (std::find(windowOpen.usedNames.top().begin(), windowOpen.usedNames.top().end(), result) != windowOpen.usedNames.top().end())

**Comment by Daandelange** [comment]
Hi,
That's very weird because both `master` and `develop` both define it correctly. [see here](https://github.com/jvcleave/ofxImGui/blob/develop/libs/imgui/src/imgui.h#L152).
If you are indeed using a clean install, can you fix it by explicitly including "imgui.h" ?
Note that I haven't tested `ofxImGui/develop` on openframeworks 0.12 but I guess some people are already using it correctly. I don't know about `master`. Are you using `develop` ?

Same for the 2nd error, it's correctly defined [here](https://github.com/jvcleave/ofxImGui/blob/develop/src/ImHelpers.h#L26) so you seem to be running into a quite strange error.

**Comment by Daandelange** [comment]
No response, closing...
