### ISSUE TITLE
opengl error

### ISSUE THREAD

**Issue by o2co2** [jvcleave/ofxImGui#22]
int main()
{
	
	ofGLWindowSettings glWindowSettings;
	glWindowSettings.width = 1280;
	glWindowSettings.height = 720;
	glWindowSettings.setGLVersion(4,1);
	ofCreateWindow(glWindowSettings);

	ofRunApp(new ofApp());
}

error：
0x0339FE7A exception thrown at (located Morphing Software debug.exe in): 0xC0000005: reading location 0x00000000 access violation occurs.
If applicable for this exception handler, the program can continue to operate safely.

**Comment by jvcleave** [comment]
with 4,1 example-demo works ok on Mac 10.11.2/AMD Radeon HD 6750M

**Comment by o2co2** [comment]
@jvcleave Thank you!
My computer is a macbook pro windows x64 nvidia geforce gt 750m.
Is there a solution to the problem?

**Comment by jvcleave** [comment]
I can't replicate it. Does the example-demo work with 4,1 for you?

**Comment by o2co2** [comment]
@jvcleave Not
Error in Fig.
![error](http://7nar31.com1.z0.glb.clouddn.com/123456.png)

**Comment by o2co2** [comment]
@jvcleave You can help me?
glWindowSettings.setGLVersion(4,1);           Not run.
glWindowSettings.setGLVersion(2,1);           ok run.

**Comment by jvcleave** [comment]
@o2co2 I don't think I can

**Comment by o2co2** [comment]
@jvcleave  g.IO.RenderDrawListsFn(&data);  Here throws an error.

**Comment by o2co2** [comment]
![error1](http://7nar31.com1.z0.glb.clouddn.com/111.PNG)
![error2](http://7nar31.com1.z0.glb.clouddn.com/222.PNG)

**Comment by o2co2** [comment]
void EngineGLFW::programmableRendererDrawLists(ImDrawData * draw_data)

glDrawElements(GL_TRIANGLES, (GLsizei)pcmd->ElemCount, GL_UNSIGNED_INT, idx_buffer_offset);

Here breakpoint occurs.

@jvcleave

**Comment by prisonerjohn** [comment]
Was this ever resolved? I'm getting a similar exception on Windows with the programmable renderer.

**Comment by jvcleave** [comment]
@prisonerjohn still unresolved - I really don't know what is going on as I don't have a Win Machine accessible to test on

**Comment by prisonerjohn** [comment]
The exception is definitely happening on the [glDrawElements line](https://github.com/jvcleave/ofxImGui/blob/master/src/EngineGLFW.cpp#L197), but I can't really figure out why. I checked the element counts uploaded vs drawn and it doesn't look like there's a buffer overrun. I have a feeling it's probably something similar to https://github.com/ocornut/imgui/pull/322

I wonder if converting all these GL objects to an ofVbo would solve it... Is there a reason why you didn't go that route? Otherwise I might try it out.

**Comment by jvcleave** [comment]
I tried it but the color conversation is slower and glScissor doesn't work.



On Feb 15, 2016, at 8:33 PM, Elie Zananiri <notifications@github.com> wrote:

The exception is definitely happening on the glDrawElements line
<https://github.com/jvcleave/ofxImGui/blob/master/src/EngineGLFW.cpp#L197>,
but I can't really figure out why. I checked the element counts uploaded vs
drawn and it doesn't look like there's a buffer overrun. I have a feeling
it's probably something similar to ocornut/imgui#322
<https://github.com/ocornut/imgui/pull/322>

I wonder if converting all these GL objects to an ofVbo would solve it...
Is there a reason why you didn't go that route? Otherwise I might try it
out.

—
Reply to this email directly or view it on GitHub
<https://github.com/jvcleave/ofxImGui/issues/22#issuecomment-184467356>.

**Comment by jvcleave** [comment]
If you guys want to try the old version that uses ofVboMesh - that is here

https://github.com/jvcleave/ofxImGui/releases/tag/OF_090_RC

**Comment by prisonerjohn** [comment]
Ok that one is running... at 3fps

**Comment by jvcleave** [comment]
Ha - it wasn't that bad before on a Mac
https://vimeo.com/137275102

**Comment by jvcleave** [comment]
@prisonerjohn is the example-demo showing this exception for you? I am using Win10/OF 9.2 and VS2015 and not seeing anything.

**Comment by prisonerjohn** [comment]
I think so, but only on the programmable pipeline... And I'm on NVIDIA (GTX 760 I think). I'm about to boot into my Windows machine and will try again in a little bit.

**Comment by prisonerjohn** [comment]
Confirming that example-demo is throwing the exception for me. I don't have a non-NVIDIA setup to test on unfortunately.

**Comment by o2co2** [comment]
This error occurs only on NVIDIA GTX 750 760 series,  On osx win will error. very strange.

**Comment by multiburst** [comment]
Same here on Linux, hardware is a NVIDIA 580...crash occours as soon as opengl version is set to 3.

**Comment by jvcleave** [comment]
@multiburst are you able to use emptyExample with Linux/Nvidia? Mine crashes right away

**Comment by multiburst** [comment]
@jvcleave example doesn't work as well, same error. only the version utilizing ofVboMesh runs, with an acceptable performance.

drivers are legacy nvidia-340xx....

**Comment by o2co2** [comment]
@jvcleave  @prisonerjohn  @multiburst  @hluisi  https://github.com/xnamahx/ofxImGui/tree/gl3.1 
You can run correctly. thank! @xnamahx

**Comment by prisonerjohn** [comment]
Cool, that branch is working for me too.

**Comment by wasawi** [comment]
Same here. That branch is working with an Nvidia card. Will this be merged somewhere in this repo?

**Comment by jvcleave** [comment]
Master now has a similar patch and should be working

**Comment by wasawi** [comment]
Thanks! yes its working.

**Comment by jvcleave** [comment]
Great - closing then :) thanks for porting @prisonerjohn
